stages:
  - build
  - deploy

update sources:
  stage: &ci_stage build 
  variables: &ci_vars
    GIT_STRATEGY: none
    SITE_PATH: /var/www/m2/magento.thecustomproductbuilder.com/current/
  script: &ci_script |-
    echo "starting update sources build job...";
    echo "=================================================";
    echo "SITE_PATH:                ${SITE_PATH}"
    echo "CI_COMMIT_REF_NAME:       ${CI_COMMIT_REF_NAME}"
    echo "CI_PROJECT_PATH_SLUG:     ${CI_PROJECT_PATH_SLUG}"
    echo "=================================================";
  only: &ci_only
    - master
  tags: &ci_tags
    - php-fpm
    
expose shell:
  stage: deploy
  only: *ci_only
  variables: *ci_vars
  tags: *ci_tags
  script: |-
    echo "exposing shell.."
    echo "=================================================";
    echo "CI_ENVIRONMENT_SLUG:      ${CI_ENVIRONMENT_SLUG}"
    echo "CI_COMMIT_REF_SLUG:       ${CI_COMMIT_REF_SLUG}"
    echo "CI_COMMIT_REF_NAME:       ${CI_COMMIT_REF_NAME}"
    echo "CI_PROJECT_PATH_SLUG:     ${CI_PROJECT_PATH_SLUG}"
    echo "=================================================";
  environment:
    name: php-fpm
    url: &ci_url https://magento.thecustomproductbuilder.com
    
.job1:
  stage: build
  script:
    echo "pull application to $CI_ENVIRONMENT_SLUG";
    sitepath="/var/www/m2/magento.thecustomproductbuilder.com/current/";
    branch="master";
    ls -lah /var;
    export;
  only:
    - master
