stages:
  - build

job1:
  stage: build
  script:
    echo "pull application to $CI_ENVIRONMENT_SLUG";
    sitepath="/var/www/m2/magento.thecustomproductbuilder.com/current/";
    branch="master";
    ls -lah /var;
    export;
  only:
    - master
  environment:
    name: cpb-demo
    url: https://royalrobbins.com/
